---
title: "poc-lm-fdr"
author: "Candace Savonen"
date: "2025-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

One linear model and compare to separate linear models. 

```{r}
devtools::load_all()
```

```{r}
gimap_data_org <- readRDS("original_data.RDS")
```

```{r}
gimap_dataset <- get_example_data("gimap") %>%
  gimap_filter() %>%
  gimap_annotate(cell_line = "HELA") %>%
  gimap_normalize(
    timepoints = "day"
  ) %>%
  calc_gi()
```

## Characterizing what has changed

```{r}
plot(gimap_data_org$gi_scores$mean_observed_cs, gimap_dataset$gi_scores$mean_observed_cs)

plot(gimap_data_org$gi_scores$mean_expected_cs, gimap_dataset$gi_scores$mean_expected_cs)
```

```{r}
plot(-log10(gimap_data_org$gi_scores$fdr) , -log10(gimap_dataset$gi_scores$fdr))

plot(gimap_data_org$gi_scores$mean_expected_cs, gimap_dataset$gi_scores$mean_expected_cs)
```

## Now

```{r}
plot_exp_v_obs_scatter(gimap_dataset)
plot_rank_scatter(gimap_dataset)
plot_volcano(gimap_dataset)
```
# Before
```{r}
plot_exp_v_obs_scatter(gimap_data_org)
plot_rank_scatter(gimap_data_org)
plot_volcano(gimap_data_org)
```
