name: Report readability

# This action only works on pull request events
on: pull_request


jobs:

    report-readability:
        name: Report readability
        runs-on: ubuntu-latest
        permissions: 
            pull-request: read
            content: read
        steps:
            - name: Checkout repo with history
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: Rebilly/lexi@v2
              with:
                  glob: '**/*.md'
